version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_USER=fileshare_user
      - DB_PASSWORD=securepassword
      - DB_NAME=fileshare
      - REDIS_HOST=redis
      - LOCAL_STORAGE_DIR=/app/uploads
    depends_on:
      - db
      - redis
    volumes:
      - uploads:/app/uploads

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=fileshare_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=fileshare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  uploads: